{
 "title": "custella",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "쿠버네티스 노드 정보", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "쿠버네티스 노드 정보",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_uname_info - 0", "legendFormat": "__auto" },
    { "expr": "node_memory_MemTotal_bytes - 0", "legendFormat": "__auto" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds)by(instance)/86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes{fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "{{interval}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total[$interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total[$interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total[$interval])) by (instance) *100",
     "legendFormat": "__auto"
    },
    { "expr": "node_netstat_Tcp_CurrEstab - 0", "legendFormat": "__auto" },
    { "expr": "node_sockstat_TCP_tw - 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "마스터 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$interval:5m])\n)"
    }
   ]
  },
  {
   "title": "apiserver 요청에 대한 응답 시간",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "프로메테우스 타겟에 대한 매트릭 수집 결과",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_targets",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "노드 별 5분간 네트워크 수신 변화율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "쿠버네티스 노드 정보",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "쿠버네티스 manifest 정보", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "네임스페이스 별 파드 개수",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네임스페이스 별 컨피그맵 개수",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "count(kube_configmap_info) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alt-shift-front 파드 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"alt-shift-front\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xauth 파드 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"xauth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "x1 네임스페이스의 디플로이먼트 상태",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"x1\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "xfds파드 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"xfds\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$namespace 네임스페이스의 디플로이먼트 개수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "count(kube_deployment_status_condition{namespace=~\"$namespace\", status=\"true\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$namespace 네임스페이스의  replicaset 개수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$namespace namespace $pod pod 정보",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}