{{- if .Values.externalSecret.serviceAccount.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xfds-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "xfds.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.dataKey }}
{{- end }}
