version: "3.9"

services:

  x1-postgres:
    image: postgres:16.2
    container_name: "x1-postgres"
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql


  x1-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: "x1-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=dev
      - KEYCLOAK_ADMIN_PASSWORD=dev
      - KC_DB=postgres
      - KC_DB_URL_HOST=x1-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=dev
      - KC_DB_PASSWORD=dev
    ports:
      - 8080:8080

  x1-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: x1-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  #Web UI to connect to databases
  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
