apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: x1
  namespace: {{ include  "argo-cd.namespace" . }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - '*'