profile: dev
appName: xbank
namespace: x1
replicaCount: 2
revisionHistoryLimit: 5
image:
  repository: 637423218787.dkr.ecr.ap-northeast-2.amazonaws.com/xbank
  tag: ccb76a14d5a1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "monitoring/java-instrumentation"
pdb:
  enabled: true
  minAvailable: 1
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
                - xbank
        topologyKey: "kubernetes.io/hostname"
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 10"]
livenessProbe:
  httpGet:
    path: /xbank/actuator/health/liveness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /xbank/actuator/health/readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
terminationGracePeriodSeconds: 30
externalSecret:
  secretStore:
    name: xbank-secret-store
  secretName: xbank-secret
  dataKey: dev/xbank
  serviceAccount:
    name: xbank
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::637423218787:role/eks-dev-custella-external-secrets
ingress:
  enabled: false
#  ingressClassName: alb
#  annotations:
#    alb.ingress.kubernetes.io/group.name: dev-custella
#    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
#    alb.ingress.kubernetes.io/load-balancer-name: dev-custella
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/target-type: ip
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:637423218787:certificate/2ca46e1b-f2d7-434a-8537-10189c2b380c
#    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#    alb.ingress.kubernetes.io/ssl-redirect: '443'
#    alb.ingress.kubernetes.io/subnets: subnet-0cfb882d43d052e3d, subnet-06bcf10b968dd617a
#  ingressRule:
#    - host: dev-xbank.custellax.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: xbank
#                port:
#                  number: 8080
resources:
  limits:
    memory: 1024Mi
  requests:
    memory: 1024Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      podsValue: 1 # Increase by 1 pods when scaling up
      periodSeconds: 15 # Evaluate over a 60-second period
    scaleDown:
      stabilizationWindowSeconds: 300
      podsValue: 1 # Decrease by 1 pod when scaling down
      periodSeconds: 15 # Evaluate over a 60-second period
