profile: dev
appName: xboa
namespace: x1
replicaCount: 2
revisionHistoryLimit: 5
image:
  repository: 637423218787.dkr.ecr.ap-northeast-2.amazonaws.com/xboa
  tag: c55bd4767248
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9001
  targetPort: 9001

ingress:
  enabled: true

podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "monitoring/java-instrumentation"
pdb:
  enabled: true
  minAvailable: 1
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
                - xboa
        topologyKey: "kubernetes.io/hostname"
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 10"]
livenessProbe:
  httpGet:
    path: /xboa/actuator/health/liveness
    port: 9001
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /xboa/actuator/health/readiness
    port: 9001
  initialDelaySeconds: 10
  periodSeconds: 10
terminationGracePeriodSeconds: 30
externalSecret:
  secretStore:
    name: xboa-secret-store
  secretName: xboa-secret
  dataKey: dev/xboa
  serviceAccount:
    name: xboa
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::637423218787:role/eks-dev-custella-external-secrets
resources:
  limits:
    memory: 1024Mi
  requests:
    memory: 1024Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      podsValue: 1 # Increase by 1 pods when scaling up
      periodSeconds: 15 # Evaluate over a 60-second period
    scaleDown:
      stabilizationWindowSeconds: 300
      podsValue: 1 # Decrease by 1 pod when scaling down
      periodSeconds: 15 # Evaluate over a 60-second period
