{{- if .Values.externalSecret.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecret.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "xauth.labels" . | nindent 4 }}
  {{- with .Values.externalSecret.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
