{{- if eq .Values.mode "prod" }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: nodepool
spec:
  template:
    metadata:
      labels:
        node: service
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [ "amd64" ]
        - key: kubernetes.io/os
          operator: In
          values: [ "linux" ]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: [ t3.large, t3a.large, m5.large, m5.xlarge, r5.large]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ ap-northeast-2a ]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [ spot ]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: service
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
{{- end }}