cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/