deploymentMode: SingleBinary

serviceAccount:
  create: true
  name: loki-storage
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::209479278227:role/eks-prod-custella-monitoring-storage

chunksCache:
  enabled: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-08-12
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: "s3"
    bucketNames:
      chunks: 209479278227-apnortheast2-loki-storage
      ruler: 209479278227-apnortheast2-loki-storage
      admin: 209479278227-apnortheast2-loki-storage
    s3:
      region: ap-northeast-2

singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0


