apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: keycloak
  {{- if or .Values.auth.annotations .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.merge" (dict "values" (list .Values.auth.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  x1-realm.json: {{ .Files.Get "realms/x1-realm.json" | b64enc }}
  kubernetes-realm.json: {{ .Files.Get "realms/kubernetes-realm.json" | b64enc }}
  blockbit-realm.json: {{ .Files.Get "realms/blockbit-realm.json" | b64enc }}