mode: dev

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::637423218787:role/eks-dev-custella-karpenter-controller

controller:
  resources:
    limits:
      memory: 1Gi
    request:
      cpu: 100m
      memory: 1Gi

additionalAnnotations:
  app: karpenter

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: DoesNotExist
            - key: eks.amazonaws.com/compute-type
              operator: In
              values:
                - fargate
#            - key: eks.amazonaws.com/nodegroup
#              operator: In
#              values:
#                - dev-custella-ng
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"

settings:
  clusterName: dev-custella
  featureGates:
    spotToSpotConsolidation: true

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus-stack