apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/devblockbit/xfds/k8s?ref=develop

images:
  - name: xfds
    newName: 637423218787.dkr.ecr.ap-northeast-2.amazonaws.com/xfds
    newTag: latest

replicas:
  - count: 2
    name: xfds

