{{- if .Values.externalSecret.serviceAccount.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStore.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecret.serviceAccount.name }}
{{- end }}