{{- if .Values.externalSecret.serviceAccount.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: webhookurl
      remoteRef:
        key: {{ .Values.externalSecret.dataKey }}
        property: webhookURL
{{- end }}
