{{- if and .Values.externalSecret.serviceAccount.create (eq .Values.mode "dev") }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ include "grafana.namespace" . }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: "dev/infra"
        property: grafanaClientId
    - secretKey: client_secret
      remoteRef:
        key: "dev/infra"
        property: grafanaClientSecret
{{- end }}
