{{- if .Values.externalSecret.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecret.serviceAccount.name }}
  namespace: {{ include "grafana.namespace" . }}
  {{- with .Values.externalSecret.serviceAccount.annotations }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "0"
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
