{{- if and .Values.externalSecret.serviceAccount.create (eq .Values.mode "dev") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ include  "argo-cd.namespace" . }}
  {{- with .Values.externalSecret.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
