{{- if and .Values.externalSecret.serviceAccount.create (eq .Values.mode "prod") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ include  "argo-cd.namespace" . }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    template:  # 시크릿 메타데이터를 설정하는 template 사용
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientSecret
      remoteRef:
        key: "prod/infra"
        property: argocdClientSecret
    - secretKey: slackToken
      remoteRef:
        key: "prod/infra"
        property: slackToken
{{/*  dataFrom:*/}}
{{/*    - extract:*/}}
{{/*        key: {{ .Values.externalSecret.dataKey }}*/}}
{{- end }}
