{{- if and .Values.externalSecret.serviceAccount.create (eq .Values.mode "prod") }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ include  "argo-cd.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
{{- end }}